### ISSUE TITLE
keep getting this messages in the error log

### ISSUE THREAD

**Issue by AndreiD** [orientechnologies/orientdb-lucene#43]
I copied the jar file, restarted the server then in the error log, every  3 seconds appears

~~~~
2015-02-13 03:45:05:655 INFO  Installing dynamic plugin 'orientdb-lucene-2.0-SNAPSHOT-dist.jar'... [OServerPluginManager]
2015-02-13 03:45:05:683 INFO  Lucene index plugin installed and active. Lucene version: LUCENE_47 [OLuceneIndexPlugin]Error on installing dynamic plugin 'lucene-index'
java.lang.IllegalStateException: Plugin 'lucene-index' already registered
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerPlugin(OServerPluginManager.java:123)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:354)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:59)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:92)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

2015-02-13 03:45:10:655 INFO  Installing dynamic plugin 'orientdb-lucene-2.0-SNAPSHOT-dist.jar'... [OServerPluginManager]
2015-02-13 03:45:10:682 INFO  Lucene index plugin installed and active. Lucene version: LUCENE_47 [OLuceneIndexPlugin]Error on installing dynamic plugin 'lucene-index'
java.lang.IllegalStateException: Plugin 'lucene-index' already registered
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerPlugin(OServerPluginManager.java:123)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:354)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:59)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:92)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

2015-02-13 03:45:15:655 INFO  Installing dynamic plugin 'orientdb-lucene-2.0-SNAPSHOT-dist.jar'... [OServerPluginManager]
2015-02-13 03:45:15:682 INFO  Lucene index plugin installed and active. Lucene version: LUCENE_47 [OLuceneIndexPlugin]Error on installing dynamic plugin 'lucene-index'
java.lang.IllegalStateException: Plugin 'lucene-index' already registered
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerPlugin(OServerPluginManager.java:123)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:354)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:59)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:92)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)


~~~~

am I doing something wrong ?

**Comment by AndreiD** [comment]
ok, so there's already a plugin lucene called "orientdb-lucene-2.0-dist.jar  " in the plugins directory.... so with the latest version there is no need to install it anymore.
