### ISSUE TITLE
OrientDB 2.1-RC3 Spatial Queries do not work

### ISSUE THREAD

**Issue by dsbaha** [orientechnologies/orientdb-lucene#52]
When trying to follow the Lucene-Spatial tutorials, I get errors w/ OrientDB 2.1-RC3.  Please see the following error;

```
{db=citydb} Error on using index pictures.lat_lon in query 'select * from pictures where [latitude, longitude] LUCENE NEAR [1, 1, {"maxdistance": 100}]'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.NullPointerException
        at com.orientechnologies.lucene.manager.OLuceneSpatialIndexManager.searchIntersect(OLuceneSpatialIndexManager.java:145)
        at com.orientechnologies.lucene.manager.OLuceneSpatialIndexManager.get(OLuceneSpatialIndexManager.java:134)
        at com.orientechnologies.lucene.OLuceneIndexEngine.get(OLuceneIndexEngine.java:118)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.get(OLuceneIndexNotUnique.java:108)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.get(OLuceneIndexNotUnique.java:36)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59)
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:272)
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:40)
        at com.orientechnologies.lucene.operator.OLuceneTextOperator.executeIndexQuery(OLuceneTextOperator.java:51)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1844)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:835)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:194)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:462)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:444)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:415)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:89)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1205)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1186)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1190)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:222)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```

**Comment by maggiolo00** [comment]
Hi @dsbaha 
could you retry with the 2.1-rc4?

**Comment by maggiolo00** [comment]
Any news about this?

**Comment by lvca** [comment]
Closed because no answer.
