### ISSUE TITLE
Orient v2.0.6 cant run plugin

### ISSUE THREAD

**Issue by stuk88** [orientechnologies/orientdb-lucene#56]
```
2015-06-26 05:59:59:864 INFO  Installing dynamic plugin 'orientdb-lucene-1.7.jar'... [OServerPluginManager]Error on installing dynamic plugin 'lucene-index'
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:264)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:343)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/db/record/ODatabaseRecord
        at com.orientechnologies.lucene.OLuceneIndexPlugin.startup(OLuceneIndexPlugin.java:55)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.orient.core.db.record.ODatabaseRecord
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
```

**Comment by stuk88** [comment]
after trying release 2.0, it all worked.
but you really should write about the releases are corresponding to the orientdb releases
