### ISSUE TITLE
Update from 2.0.5 to 2.0.12 fails with Exception 

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-lucene#57]
I was working 6 month on version 2.0.5 of OrientDB. All was fine. Today I wanted to update to the latest release 2.0.12. But when I now wanted to create my database within my Java import I get an error within the Lucene implementation.

It seems that there is something wrong with the Lucene Jar file. Btw I did not change the Lucene version. It is still *orientdb-lucene-2.0-SNAPSHOT-dist.jar*. I also redownloaded it from here. Still the same error.

```java
Exception in thread "main" java.lang.AbstractMethodError
	at com.orientechnologies.orient.core.index.OIndexes.createIndex(OIndexes.java:150)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:155)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1444)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:262)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1194)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeCommand(OCommandExecutorScript.java:324)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:264)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:148)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:93)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:83)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1194)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at kwoxer.de.OrientDB.createObject_VertexAbstractName(OrientDB.java:80)
	at kwoxer.de.OrientDBMain.main(OrientDBMain.java:32)
```

**Comment by maggiolo00** [comment]
hi @kwoxer 
how did you upgrade OrientDB?

**Comment by kwoxer** [comment]
Yes I replace all the lib files, and for sure changed the references in my Java project =)

There are no errors, just the Lucene plugin does not work within the import anymore. And giving me the error log above.

**Comment by maggiolo00** [comment]
Did you replace also the orientdb-lucene jar?

**Comment by kwoxer** [comment]
If you mean the *orientdb-lucene-2.0-SNAPSHOT-dist.jar*, no, I first tested with my old one. But it was the same error. And also after downloading latest from Github the same error remains.

**Comment by maggiolo00** [comment]
No the one that is in the 2.0.12 distribution

**Comment by kwoxer** [comment]
There is none :D damnit, why so?

**Comment by kwoxer** [comment]
Ohh does you mean the one in the *plugins* folder?
